 version: "3.3"

 services:
   mysql:
     image: mysql:5.7
     volumes:
       - mysql-data:/var/lib/mysql
     ports:
       - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: todos

 volumes:
   mysql-data:
